### PR TITLE
Changed attribute names to be less generic to avoid conflicts

### PR DESCRIPTION
**Pull request by BWMuller**
Changed attribute names to less generic versions to avoid naming conflicts with other libraries such as Instabug. 
Moved library dependant classpaths to the library

### CODE REVIEW

**Comment by lopspower** [comment]
I don't understand the reason for your request to pull. I already changed attribute names to avoid conflicts.

**Comment by BWMuller** [comment]
Pull the library a few hours ago. The style attribute names eg. civ_border are quite generic. There are several libraries that contain a CircleImageView with attributes starting in civ. If multiple libraries have the same attribute names conflicts occur.

**Comment by lopspower** [comment]
What is the interest of adding two libraries to make circular images in the same project?

**Comment by BWMuller** [comment]
Some libraries include their own versions of features such as the Circular Image View however they implement them horribly or do not make them public. This then causes conflicts with other such libraries. 

In this case Instabug has a Circlular Image View included in its libraries, however it breaks horribly and is very buggy as is.
Also your library is exactly what I am looking for.

**Pull request closed without merging**
